// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: kadsrnet.proto

package kadsrnet

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src  []byte   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst  []byte   `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Path []uint32 `protobuf:"varint,3,rep,packed,name=path,proto3" json:"path,omitempty"`
	// Types that are assignable to Body:
	//	*Message_Data
	//	*Message_QueryRoutes
	//	*Message_RouteList
	Body  isMessage_Body `protobuf_oneof:"body"`
	Nonce []byte         `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sig   []byte         `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kadsrnet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_kadsrnet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_kadsrnet_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSrc() []byte {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *Message) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Message) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (m *Message) GetBody() isMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x, ok := x.GetBody().(*Message_Data); ok {
		return x.Data
	}
	return nil
}

func (x *Message) GetQueryRoutes() *QueryRoutes {
	if x, ok := x.GetBody().(*Message_QueryRoutes); ok {
		return x.QueryRoutes
	}
	return nil
}

func (x *Message) GetRouteList() *RouteList {
	if x, ok := x.GetBody().(*Message_RouteList); ok {
		return x.RouteList
	}
	return nil
}

func (x *Message) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Message) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type isMessage_Body interface {
	isMessage_Body()
}

type Message_Data struct {
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3,oneof"`
}

type Message_QueryRoutes struct {
	QueryRoutes *QueryRoutes `protobuf:"bytes,7,opt,name=query_routes,json=queryRoutes,proto3,oneof"`
}

type Message_RouteList struct {
	RouteList *RouteList `protobuf:"bytes,8,opt,name=route_list,json=routeList,proto3,oneof"`
}

func (*Message_Data) isMessage_Body() {}

func (*Message_QueryRoutes) isMessage_Body() {}

func (*Message_RouteList) isMessage_Body() {}

type QueryRoutes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Max uint32 `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *QueryRoutes) Reset() {
	*x = QueryRoutes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kadsrnet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRoutes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoutes) ProtoMessage() {}

func (x *QueryRoutes) ProtoReflect() protoreflect.Message {
	mi := &file_kadsrnet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoutes.ProtoReflect.Descriptor instead.
func (*QueryRoutes) Descriptor() ([]byte, []int) {
	return file_kadsrnet_proto_rawDescGZIP(), []int{1}
}

func (x *QueryRoutes) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dst  []byte   `protobuf:"bytes,1,opt,name=dst,proto3" json:"dst,omitempty"`
	Path []uint32 `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kadsrnet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_kadsrnet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_kadsrnet_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Route) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

type RouteList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes []*Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Src    []byte   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
}

func (x *RouteList) Reset() {
	*x = RouteList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kadsrnet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteList) ProtoMessage() {}

func (x *RouteList) ProtoReflect() protoreflect.Message {
	mi := &file_kadsrnet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteList.ProtoReflect.Descriptor instead.
func (*RouteList) Descriptor() ([]byte, []int) {
	return file_kadsrnet_proto_rawDescGZIP(), []int{3}
}

func (x *RouteList) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteList) GetSrc() []byte {
	if x != nil {
		return x.Src
	}
	return nil
}

var File_kadsrnet_proto protoreflect.FileDescriptor

var file_kadsrnet_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x61, 0x64, 0x73, 0x72, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xe7, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x64, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x0c, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x48, 0x00,
	0x52, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x2b, 0x0a,
	0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73,
	0x69, 0x67, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x1f, 0x0a, 0x0b, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x2d, 0x0a, 0x05, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x3d, 0x0a, 0x09, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x72, 0x63, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2f,
	0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x61, 0x64, 0x73,
	0x72, 0x6e, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kadsrnet_proto_rawDescOnce sync.Once
	file_kadsrnet_proto_rawDescData = file_kadsrnet_proto_rawDesc
)

func file_kadsrnet_proto_rawDescGZIP() []byte {
	file_kadsrnet_proto_rawDescOnce.Do(func() {
		file_kadsrnet_proto_rawDescData = protoimpl.X.CompressGZIP(file_kadsrnet_proto_rawDescData)
	})
	return file_kadsrnet_proto_rawDescData
}

var file_kadsrnet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kadsrnet_proto_goTypes = []interface{}{
	(*Message)(nil),     // 0: Message
	(*QueryRoutes)(nil), // 1: QueryRoutes
	(*Route)(nil),       // 2: Route
	(*RouteList)(nil),   // 3: RouteList
}
var file_kadsrnet_proto_depIdxs = []int32{
	1, // 0: Message.query_routes:type_name -> QueryRoutes
	3, // 1: Message.route_list:type_name -> RouteList
	2, // 2: RouteList.routes:type_name -> Route
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kadsrnet_proto_init() }
func file_kadsrnet_proto_init() {
	if File_kadsrnet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kadsrnet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kadsrnet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRoutes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kadsrnet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kadsrnet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kadsrnet_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_Data)(nil),
		(*Message_QueryRoutes)(nil),
		(*Message_RouteList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kadsrnet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kadsrnet_proto_goTypes,
		DependencyIndexes: file_kadsrnet_proto_depIdxs,
		MessageInfos:      file_kadsrnet_proto_msgTypes,
	}.Build()
	File_kadsrnet_proto = out.File
	file_kadsrnet_proto_rawDesc = nil
	file_kadsrnet_proto_goTypes = nil
	file_kadsrnet_proto_depIdxs = nil
}
