// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: inet256.proto

package inet256grpc

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GenerateKeyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *GenerateKeyRes) Reset() {
	*x = GenerateKeyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRes) ProtoMessage() {}

func (x *GenerateKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRes.ProtoReflect.Descriptor instead.
func (*GenerateKeyRes) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateKeyRes) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type LookupSelfReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *LookupSelfReq) Reset() {
	*x = LookupSelfReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupSelfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupSelfReq) ProtoMessage() {}

func (x *LookupSelfReq) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupSelfReq.ProtoReflect.Descriptor instead.
func (*LookupSelfReq) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{1}
}

func (x *LookupSelfReq) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type LookupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetAddr []byte `protobuf:"bytes,1,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"`
}

func (x *LookupReq) Reset() {
	*x = LookupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupReq) ProtoMessage() {}

func (x *LookupReq) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupReq.ProtoReflect.Descriptor instead.
func (*LookupReq) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{2}
}

func (x *LookupReq) GetTargetAddr() []byte {
	if x != nil {
		return x.TargetAddr
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr      []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{3}
}

func (x *PeerInfo) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *PeerInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type ConnectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte    `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Datagram   *Datagram `protobuf:"bytes,2,opt,name=datagram,proto3" json:"datagram,omitempty"`
}

func (x *ConnectMsg) Reset() {
	*x = ConnectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMsg) ProtoMessage() {}

func (x *ConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMsg.ProtoReflect.Descriptor instead.
func (*ConnectMsg) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectMsg) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *ConnectMsg) GetDatagram() *Datagram {
	if x != nil {
		return x.Datagram
	}
	return nil
}

type Datagram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src     []byte `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst     []byte `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Datagram) Reset() {
	*x = Datagram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Datagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datagram) ProtoMessage() {}

func (x *Datagram) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datagram.ProtoReflect.Descriptor instead.
func (*Datagram) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{5}
}

func (x *Datagram) GetSrc() []byte {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *Datagram) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Datagram) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_inet256_proto protoreflect.FileDescriptor

var file_inet256_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x30, 0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x53, 0x65, 0x6c, 0x66, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x2c, 0x0a, 0x09, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0x3d, 0x0a, 0x08, 0x50, 0x65, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x5c, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x67, 0x72,
	0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32,
	0x35, 0x36, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x67, 0x72, 0x61, 0x6d, 0x22, 0x48, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x67, 0x72, 0x61,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32,
	0xf4, 0x01, 0x0a, 0x07, 0x49, 0x4e, 0x45, 0x54, 0x32, 0x35, 0x36, 0x12, 0x40, 0x0a, 0x0b, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x17, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x0a, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x53, 0x65, 0x6c, 0x66, 0x12, 0x16, 0x2e, 0x69, 0x6e,
	0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x53, 0x65, 0x6c, 0x66,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x50, 0x65,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x12, 0x12, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36,
	0x2e, 0x50, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x13, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x13, 0x2e, 0x69, 0x6e,
	0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2f, 0x69, 0x6e, 0x65,
	0x74, 0x32, 0x35, 0x36, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inet256_proto_rawDescOnce sync.Once
	file_inet256_proto_rawDescData = file_inet256_proto_rawDesc
)

func file_inet256_proto_rawDescGZIP() []byte {
	file_inet256_proto_rawDescOnce.Do(func() {
		file_inet256_proto_rawDescData = protoimpl.X.CompressGZIP(file_inet256_proto_rawDescData)
	})
	return file_inet256_proto_rawDescData
}

var file_inet256_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inet256_proto_goTypes = []interface{}{
	(*GenerateKeyRes)(nil), // 0: inet256.GenerateKeyRes
	(*LookupSelfReq)(nil),  // 1: inet256.LookupSelfReq
	(*LookupReq)(nil),      // 2: inet256.LookupReq
	(*PeerInfo)(nil),       // 3: inet256.PeerInfo
	(*ConnectMsg)(nil),     // 4: inet256.ConnectMsg
	(*Datagram)(nil),       // 5: inet256.Datagram
	(*empty.Empty)(nil),    // 6: google.protobuf.Empty
}
var file_inet256_proto_depIdxs = []int32{
	5, // 0: inet256.ConnectMsg.datagram:type_name -> inet256.Datagram
	6, // 1: inet256.INET256.GenerateKey:input_type -> google.protobuf.Empty
	1, // 2: inet256.INET256.LookupSelf:input_type -> inet256.LookupSelfReq
	2, // 3: inet256.INET256.Lookup:input_type -> inet256.LookupReq
	4, // 4: inet256.INET256.Connect:input_type -> inet256.ConnectMsg
	0, // 5: inet256.INET256.GenerateKey:output_type -> inet256.GenerateKeyRes
	3, // 6: inet256.INET256.LookupSelf:output_type -> inet256.PeerInfo
	3, // 7: inet256.INET256.Lookup:output_type -> inet256.PeerInfo
	4, // 8: inet256.INET256.Connect:output_type -> inet256.ConnectMsg
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inet256_proto_init() }
func file_inet256_proto_init() {
	if File_inet256_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inet256_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKeyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupSelfReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Datagram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inet256_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inet256_proto_goTypes,
		DependencyIndexes: file_inet256_proto_depIdxs,
		MessageInfos:      file_inet256_proto_msgTypes,
	}.Build()
	File_inet256_proto = out.File
	file_inet256_proto_rawDesc = nil
	file_inet256_proto_goTypes = nil
	file_inet256_proto_depIdxs = nil
}
