// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: inet256.proto

package inet256grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateKeyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *GenerateKeyRes) Reset() {
	*x = GenerateKeyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRes) ProtoMessage() {}

func (x *GenerateKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRes.ProtoReflect.Descriptor instead.
func (*GenerateKeyRes) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateKeyRes) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type FindAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Prefix     []byte `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Nbits      uint32 `protobuf:"varint,3,opt,name=nbits,proto3" json:"nbits,omitempty"`
}

func (x *FindAddrReq) Reset() {
	*x = FindAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAddrReq) ProtoMessage() {}

func (x *FindAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAddrReq.ProtoReflect.Descriptor instead.
func (*FindAddrReq) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{1}
}

func (x *FindAddrReq) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *FindAddrReq) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *FindAddrReq) GetNbits() uint32 {
	if x != nil {
		return x.Nbits
	}
	return 0
}

type FindAddrRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr      []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *FindAddrRes) Reset() {
	*x = FindAddrRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAddrRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAddrRes) ProtoMessage() {}

func (x *FindAddrRes) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAddrRes.ProtoReflect.Descriptor instead.
func (*FindAddrRes) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{2}
}

func (x *FindAddrRes) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *FindAddrRes) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type LookupPublicKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Target     []byte `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *LookupPublicKeyReq) Reset() {
	*x = LookupPublicKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupPublicKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPublicKeyReq) ProtoMessage() {}

func (x *LookupPublicKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPublicKeyReq.ProtoReflect.Descriptor instead.
func (*LookupPublicKeyReq) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{3}
}

func (x *LookupPublicKeyReq) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *LookupPublicKeyReq) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

type LookupPublicKeyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *LookupPublicKeyRes) Reset() {
	*x = LookupPublicKeyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupPublicKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPublicKeyRes) ProtoMessage() {}

func (x *LookupPublicKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPublicKeyRes.ProtoReflect.Descriptor instead.
func (*LookupPublicKeyRes) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{4}
}

func (x *LookupPublicKeyRes) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type ConnectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Init        *ConnectInit `protobuf:"bytes,1,opt,name=init,proto3" json:"init,omitempty"`
	Established []byte       `protobuf:"bytes,2,opt,name=established,proto3" json:"established,omitempty"`
	Datagram    *Datagram    `protobuf:"bytes,3,opt,name=datagram,proto3" json:"datagram,omitempty"`
}

func (x *ConnectMsg) Reset() {
	*x = ConnectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMsg) ProtoMessage() {}

func (x *ConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMsg.ProtoReflect.Descriptor instead.
func (*ConnectMsg) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectMsg) GetInit() *ConnectInit {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *ConnectMsg) GetEstablished() []byte {
	if x != nil {
		return x.Established
	}
	return nil
}

func (x *ConnectMsg) GetDatagram() *Datagram {
	if x != nil {
		return x.Datagram
	}
	return nil
}

type ConnectInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *ConnectInit) Reset() {
	*x = ConnectInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInit) ProtoMessage() {}

func (x *ConnectInit) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInit.ProtoReflect.Descriptor instead.
func (*ConnectInit) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectInit) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type Datagram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src     []byte `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst     []byte `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Datagram) Reset() {
	*x = Datagram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Datagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datagram) ProtoMessage() {}

func (x *Datagram) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datagram.ProtoReflect.Descriptor instead.
func (*Datagram) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{7}
}

func (x *Datagram) GetSrc() []byte {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *Datagram) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Datagram) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MTUReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Target     []byte `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *MTUReq) Reset() {
	*x = MTUReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MTUReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTUReq) ProtoMessage() {}

func (x *MTUReq) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTUReq.ProtoReflect.Descriptor instead.
func (*MTUReq) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{8}
}

func (x *MTUReq) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *MTUReq) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

type MTURes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Mtu        int64  `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (x *MTURes) Reset() {
	*x = MTURes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MTURes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTURes) ProtoMessage() {}

func (x *MTURes) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTURes.ProtoReflect.Descriptor instead.
func (*MTURes) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{9}
}

func (x *MTURes) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *MTURes) GetMtu() int64 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type PeerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr     []byte           `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	LastSeen map[string]int64 `protobuf:"bytes,2,rep,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{10}
}

func (x *PeerStatus) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *PeerStatus) GetLastSeen() map[string]int64 {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalAddr      []byte        `protobuf:"bytes,1,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	TransportAddrs []string      `protobuf:"bytes,2,rep,name=transport_addrs,json=transportAddrs,proto3" json:"transport_addrs,omitempty"`
	PeerStatus     []*PeerStatus `protobuf:"bytes,3,rep,name=peer_status,json=peerStatus,proto3" json:"peer_status,omitempty"`
	RunningNodes   [][]byte      `protobuf:"bytes,4,rep,name=running_nodes,json=runningNodes,proto3" json:"running_nodes,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{11}
}

func (x *Status) GetLocalAddr() []byte {
	if x != nil {
		return x.LocalAddr
	}
	return nil
}

func (x *Status) GetTransportAddrs() []string {
	if x != nil {
		return x.TransportAddrs
	}
	return nil
}

func (x *Status) GetPeerStatus() []*PeerStatus {
	if x != nil {
		return x.PeerStatus
	}
	return nil
}

func (x *Status) GetRunningNodes() [][]byte {
	if x != nil {
		return x.RunningNodes
	}
	return nil
}

type DropReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *DropReq) Reset() {
	*x = DropReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropReq) ProtoMessage() {}

func (x *DropReq) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropReq.ProtoReflect.Descriptor instead.
func (*DropReq) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{12}
}

func (x *DropReq) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type DropRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropRes) Reset() {
	*x = DropRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inet256_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropRes) ProtoMessage() {}

func (x *DropRes) ProtoReflect() protoreflect.Message {
	mi := &file_inet256_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropRes.ProtoReflect.Descriptor instead.
func (*DropRes) Descriptor() ([]byte, []int) {
	return file_inet256_proto_rawDescGZIP(), []int{13}
}

var File_inet256_proto protoreflect.FileDescriptor

var file_inet256_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x5c, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x62, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6e, 0x62, 0x69, 0x74, 0x73, 0x22, 0x40, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x64,
	0x64, 0x72, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x4d, 0x0a, 0x12, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x33, 0x0a, 0x12, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x87, 0x01, 0x0a,
	0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x04, 0x69,
	0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x65, 0x74,
	0x32, 0x35, 0x36, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x52,
	0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x65, 0x73, 0x74, 0x61,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x67,
	0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x65, 0x74,
	0x32, 0x35, 0x36, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x22, 0x2e, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x48, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x67, 0x72,
	0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x41, 0x0a, 0x06, 0x4d, 0x54, 0x55, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x3b, 0x0a, 0x06, 0x4d, 0x54, 0x55, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x74, 0x75,
	0x22, 0x9d, 0x01, 0x0a, 0x0a, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x12, 0x3e, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36,
	0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x4c, 0x61, 0x73, 0x74,
	0x53, 0x65, 0x65, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53,
	0x65, 0x65, 0x6e, 0x1a, 0x3b, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xab, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32,
	0x35, 0x36, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x70,
	0x65, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x0c, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x2a,
	0x0a, 0x07, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x09, 0x0a, 0x07, 0x44, 0x72,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x32, 0xe8, 0x02, 0x0a, 0x07, 0x49, 0x4e, 0x45, 0x54, 0x32, 0x35,
	0x36, 0x12, 0x40, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32,
	0x35, 0x36, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0f, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36,
	0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x38, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14,
	0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x64, 0x64,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x03,
	0x4d, 0x54, 0x55, 0x12, 0x0f, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x4d, 0x54,
	0x55, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x4d,
	0x54, 0x55, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x12, 0x13, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x13, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35,
	0x36, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x2c, 0x0a, 0x04, 0x44, 0x72, 0x6f, 0x70, 0x12, 0x10, 0x2e, 0x69, 0x6e, 0x65,
	0x74, 0x32, 0x35, 0x36, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x69,
	0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x32, 0x3f, 0x0a, 0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x36, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f,
	0x2e, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x32, 0x35, 0x36, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inet256_proto_rawDescOnce sync.Once
	file_inet256_proto_rawDescData = file_inet256_proto_rawDesc
)

func file_inet256_proto_rawDescGZIP() []byte {
	file_inet256_proto_rawDescOnce.Do(func() {
		file_inet256_proto_rawDescData = protoimpl.X.CompressGZIP(file_inet256_proto_rawDescData)
	})
	return file_inet256_proto_rawDescData
}

var file_inet256_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_inet256_proto_goTypes = []interface{}{
	(*GenerateKeyRes)(nil),     // 0: inet256.GenerateKeyRes
	(*FindAddrReq)(nil),        // 1: inet256.FindAddrReq
	(*FindAddrRes)(nil),        // 2: inet256.FindAddrRes
	(*LookupPublicKeyReq)(nil), // 3: inet256.LookupPublicKeyReq
	(*LookupPublicKeyRes)(nil), // 4: inet256.LookupPublicKeyRes
	(*ConnectMsg)(nil),         // 5: inet256.ConnectMsg
	(*ConnectInit)(nil),        // 6: inet256.ConnectInit
	(*Datagram)(nil),           // 7: inet256.Datagram
	(*MTUReq)(nil),             // 8: inet256.MTUReq
	(*MTURes)(nil),             // 9: inet256.MTURes
	(*PeerStatus)(nil),         // 10: inet256.PeerStatus
	(*Status)(nil),             // 11: inet256.Status
	(*DropReq)(nil),            // 12: inet256.DropReq
	(*DropRes)(nil),            // 13: inet256.DropRes
	nil,                        // 14: inet256.PeerStatus.LastSeenEntry
	(*emptypb.Empty)(nil),      // 15: google.protobuf.Empty
}
var file_inet256_proto_depIdxs = []int32{
	6,  // 0: inet256.ConnectMsg.init:type_name -> inet256.ConnectInit
	7,  // 1: inet256.ConnectMsg.datagram:type_name -> inet256.Datagram
	14, // 2: inet256.PeerStatus.last_seen:type_name -> inet256.PeerStatus.LastSeenEntry
	10, // 3: inet256.Status.peer_status:type_name -> inet256.PeerStatus
	15, // 4: inet256.INET256.GenerateKey:input_type -> google.protobuf.Empty
	3,  // 5: inet256.INET256.LookupPublicKey:input_type -> inet256.LookupPublicKeyReq
	1,  // 6: inet256.INET256.FindAddr:input_type -> inet256.FindAddrReq
	8,  // 7: inet256.INET256.MTU:input_type -> inet256.MTUReq
	5,  // 8: inet256.INET256.Connect:input_type -> inet256.ConnectMsg
	12, // 9: inet256.INET256.Drop:input_type -> inet256.DropReq
	15, // 10: inet256.Admin.GetStatus:input_type -> google.protobuf.Empty
	0,  // 11: inet256.INET256.GenerateKey:output_type -> inet256.GenerateKeyRes
	4,  // 12: inet256.INET256.LookupPublicKey:output_type -> inet256.LookupPublicKeyRes
	2,  // 13: inet256.INET256.FindAddr:output_type -> inet256.FindAddrRes
	9,  // 14: inet256.INET256.MTU:output_type -> inet256.MTURes
	5,  // 15: inet256.INET256.Connect:output_type -> inet256.ConnectMsg
	13, // 16: inet256.INET256.Drop:output_type -> inet256.DropRes
	11, // 17: inet256.Admin.GetStatus:output_type -> inet256.Status
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_inet256_proto_init() }
func file_inet256_proto_init() {
	if File_inet256_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inet256_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKeyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAddrRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupPublicKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupPublicKeyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Datagram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MTUReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MTURes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inet256_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inet256_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_inet256_proto_goTypes,
		DependencyIndexes: file_inet256_proto_depIdxs,
		MessageInfos:      file_inet256_proto_msgTypes,
	}.Build()
	File_inet256_proto = out.File
	file_inet256_proto_rawDesc = nil
	file_inet256_proto_goTypes = nil
	file_inet256_proto_depIdxs = nil
}
