// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: inet256.proto

package inet256grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// INET256Client is the client API for INET256 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type INET256Client interface {
	GenerateKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GenerateKeyRes, error)
	LookupPublicKey(ctx context.Context, in *LookupPublicKeyReq, opts ...grpc.CallOption) (*LookupPublicKeyRes, error)
	FindAddr(ctx context.Context, in *FindAddrReq, opts ...grpc.CallOption) (*FindAddrRes, error)
	MTU(ctx context.Context, in *MTUReq, opts ...grpc.CallOption) (*MTURes, error)
	// Connect starts a session for sending and receiving messages
	// The first message must contain a private key. The corresponding public key will
	// be used to derive an address
	Connect(ctx context.Context, opts ...grpc.CallOption) (INET256_ConnectClient, error)
	// Drop disconnects all connected sessions for a given private key.
	Drop(ctx context.Context, in *DropReq, opts ...grpc.CallOption) (*DropRes, error)
}

type iNET256Client struct {
	cc grpc.ClientConnInterface
}

func NewINET256Client(cc grpc.ClientConnInterface) INET256Client {
	return &iNET256Client{cc}
}

func (c *iNET256Client) GenerateKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GenerateKeyRes, error) {
	out := new(GenerateKeyRes)
	err := c.cc.Invoke(ctx, "/inet256.INET256/GenerateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNET256Client) LookupPublicKey(ctx context.Context, in *LookupPublicKeyReq, opts ...grpc.CallOption) (*LookupPublicKeyRes, error) {
	out := new(LookupPublicKeyRes)
	err := c.cc.Invoke(ctx, "/inet256.INET256/LookupPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNET256Client) FindAddr(ctx context.Context, in *FindAddrReq, opts ...grpc.CallOption) (*FindAddrRes, error) {
	out := new(FindAddrRes)
	err := c.cc.Invoke(ctx, "/inet256.INET256/FindAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNET256Client) MTU(ctx context.Context, in *MTUReq, opts ...grpc.CallOption) (*MTURes, error) {
	out := new(MTURes)
	err := c.cc.Invoke(ctx, "/inet256.INET256/MTU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNET256Client) Connect(ctx context.Context, opts ...grpc.CallOption) (INET256_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &INET256_ServiceDesc.Streams[0], "/inet256.INET256/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &iNET256ConnectClient{stream}
	return x, nil
}

type INET256_ConnectClient interface {
	Send(*ConnectMsg) error
	Recv() (*ConnectMsg, error)
	grpc.ClientStream
}

type iNET256ConnectClient struct {
	grpc.ClientStream
}

func (x *iNET256ConnectClient) Send(m *ConnectMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iNET256ConnectClient) Recv() (*ConnectMsg, error) {
	m := new(ConnectMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iNET256Client) Drop(ctx context.Context, in *DropReq, opts ...grpc.CallOption) (*DropRes, error) {
	out := new(DropRes)
	err := c.cc.Invoke(ctx, "/inet256.INET256/Drop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// INET256Server is the server API for INET256 service.
// All implementations must embed UnimplementedINET256Server
// for forward compatibility
type INET256Server interface {
	GenerateKey(context.Context, *emptypb.Empty) (*GenerateKeyRes, error)
	LookupPublicKey(context.Context, *LookupPublicKeyReq) (*LookupPublicKeyRes, error)
	FindAddr(context.Context, *FindAddrReq) (*FindAddrRes, error)
	MTU(context.Context, *MTUReq) (*MTURes, error)
	// Connect starts a session for sending and receiving messages
	// The first message must contain a private key. The corresponding public key will
	// be used to derive an address
	Connect(INET256_ConnectServer) error
	// Drop disconnects all connected sessions for a given private key.
	Drop(context.Context, *DropReq) (*DropRes, error)
	mustEmbedUnimplementedINET256Server()
}

// UnimplementedINET256Server must be embedded to have forward compatible implementations.
type UnimplementedINET256Server struct {
}

func (UnimplementedINET256Server) GenerateKey(context.Context, *emptypb.Empty) (*GenerateKeyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKey not implemented")
}
func (UnimplementedINET256Server) LookupPublicKey(context.Context, *LookupPublicKeyReq) (*LookupPublicKeyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupPublicKey not implemented")
}
func (UnimplementedINET256Server) FindAddr(context.Context, *FindAddrReq) (*FindAddrRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAddr not implemented")
}
func (UnimplementedINET256Server) MTU(context.Context, *MTUReq) (*MTURes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MTU not implemented")
}
func (UnimplementedINET256Server) Connect(INET256_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedINET256Server) Drop(context.Context, *DropReq) (*DropRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drop not implemented")
}
func (UnimplementedINET256Server) mustEmbedUnimplementedINET256Server() {}

// UnsafeINET256Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to INET256Server will
// result in compilation errors.
type UnsafeINET256Server interface {
	mustEmbedUnimplementedINET256Server()
}

func RegisterINET256Server(s grpc.ServiceRegistrar, srv INET256Server) {
	s.RegisterService(&INET256_ServiceDesc, srv)
}

func _INET256_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INET256Server).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inet256.INET256/GenerateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INET256Server).GenerateKey(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _INET256_LookupPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupPublicKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INET256Server).LookupPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inet256.INET256/LookupPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INET256Server).LookupPublicKey(ctx, req.(*LookupPublicKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INET256_FindAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAddrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INET256Server).FindAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inet256.INET256/FindAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INET256Server).FindAddr(ctx, req.(*FindAddrReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INET256_MTU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MTUReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INET256Server).MTU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inet256.INET256/MTU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INET256Server).MTU(ctx, req.(*MTUReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INET256_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(INET256Server).Connect(&iNET256ConnectServer{stream})
}

type INET256_ConnectServer interface {
	Send(*ConnectMsg) error
	Recv() (*ConnectMsg, error)
	grpc.ServerStream
}

type iNET256ConnectServer struct {
	grpc.ServerStream
}

func (x *iNET256ConnectServer) Send(m *ConnectMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iNET256ConnectServer) Recv() (*ConnectMsg, error) {
	m := new(ConnectMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _INET256_Drop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INET256Server).Drop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inet256.INET256/Drop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INET256Server).Drop(ctx, req.(*DropReq))
	}
	return interceptor(ctx, in, info, handler)
}

// INET256_ServiceDesc is the grpc.ServiceDesc for INET256 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var INET256_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inet256.INET256",
	HandlerType: (*INET256Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKey",
			Handler:    _INET256_GenerateKey_Handler,
		},
		{
			MethodName: "LookupPublicKey",
			Handler:    _INET256_LookupPublicKey_Handler,
		},
		{
			MethodName: "FindAddr",
			Handler:    _INET256_FindAddr_Handler,
		},
		{
			MethodName: "MTU",
			Handler:    _INET256_MTU_Handler,
		},
		{
			MethodName: "Drop",
			Handler:    _INET256_Drop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _INET256_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "inet256.proto",
}

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/inet256.Admin/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	GetStatus(context.Context, *emptypb.Empty) (*Status, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) GetStatus(context.Context, *emptypb.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inet256.Admin/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inet256.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Admin_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inet256.proto",
}
